version: "3"

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=agent
    volumes:
      - /home/volkov/dev/db/postgres:/var/lib/postgresql/data