version: "3"

services:
  db:
    image: postgres
    networks:
      - agent-net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=agent
    volumes:
      - /home/volkov/dev/dataBase/postgres:/var/lib/postgresql/data

networks:
  agent-net:
    driver: bridge
